# Generated by Django 2.0.4 on 2018-04-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vvebo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.TextField(default='', max_length=1000)),
                ('user_id', models.TextField(default='', max_length=1000)),
                ('user_name', models.TextField(default='', max_length=1000)),
                ('time', models.CharField(default='', max_length=1000)),
                ('comment', models.TextField(default='', max_length=1000)),
                ('shoucang', models.IntegerField(default=0)),
                ('zhuanfa', models.IntegerField(default=0)),
                ('pinglun', models.IntegerField(default=0)),
                ('dianzan', models.IntegerField(default=0)),
                ('device', models.TextField(default='', max_length=1000)),
                ('url', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='wechat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.TextField(default='', max_length=1000)),
                ('article_title', models.TextField(default='', max_length=1000)),
                ('article_url', models.TextField(default='', max_length=1000)),
                ('article_imgs', models.TextField(default='', max_length=1000)),
                ('comment', models.TextField(default='', max_length=1000)),
                ('time', models.TextField(default='', max_length=1000)),
                ('gzh_profile_url', models.TextField(default='', max_length=1000)),
                ('gzh_headimage', models.TextField(default='', max_length=1000)),
                ('user_name', models.TextField(default='', max_length=1000)),
                ('gzh_isv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Zhihu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(default='', max_length=100)),
                ('question_id', models.CharField(default='', max_length=20)),
                ('question_name', models.TextField(default='', max_length=100)),
                ('answer_id', models.CharField(default='', max_length=20)),
                ('comment', models.TextField(default='', max_length=30000)),
                ('time', models.CharField(default='', max_length=20)),
                ('voteup_count', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
