# Generated by Django 2.0.4 on 2018-04-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCICApp', '0002_auto_20180424_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvebo',
            name='dianzan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vvebo',
            name='pinglun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vvebo',
            name='shoucang',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vvebo',
            name='zhuanfa',
            field=models.IntegerField(default=0),
        ),
    ]
